### ISSUE TITLE
Knowledge2 tiers not informing orientations in FGS

### ISSUE THREAD

**Issue by lizziesilver** [cmu-phil/tetrad#150]
As a test case for Knowledge2, I ran FGS on the [charity.txt](http://www.phil.cmu.edu/projects/tetrad_download/download/workshop/Data/charity.txt) data. I created a Knowledge2 object and set the first tier to be "TangibilityCondition" and the second tier to include all other variables.

The output pattern includes an undirected edge between TangibilityCondition and Sympathy. Given the background knowledge, there's only one possible orientation for this edge, but FGS is not inferring the orientation. Is that intentional? 

I made sure the Knowledge2 object was affecting the behavior of FGS. If, in addition to the tiers, I set the edge from Sympathy to TangibilityCondition to be forbidden, then FGS produced a pattern with no adjacency between Sympathy and TangibilityCondition. 

I'm using the latest version of the development branch of Tetrad (pulled at 10pm EST on March 9, 2016).

**Comment by jdramsey** [comment]
Thanks. I looked and when FGS was unorienting parents of a node (because it
only had one), it wasn't checking for required edges. Let me fix that.

On Thu, Mar 10, 2016 at 1:09 AM, Lizzie Silver <notifications@github.com>
wrote:

> As a test case for Knowledge2, I ran FGS on the charity.txt
> <http://www.phil.cmu.edu/projects/tetrad_download/download/workshop/Data/charity.txt>
> data. I created a Knowledge2 object and set the first tier to be
> "TangibilityCondition" and the second tier to include all other variables.
>
> The output pattern includes an undirected edge between
> TangibilityCondition and Sympathy. Given the background knowledge, there's
> only one possible orientation for this edge, but FGS is not inferring the
> orientation. Is that intentional?
>
> I made sure the Knowledge2 object was affecting the behavior of FGS. If,
> in addition to the tiers, I set the edge from Sympathy to
> TangibilityCondition to be forbidden, then FGS produced a pattern with no
> adjacency between Sympathy and TangibilityCondition.
>
> I'm using the latest version of the development branch of Tetrad (pulled
> at 10pm EST on March 9, 2016).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cmu-phil/tetrad/issues/150>.
>



-- 
Joseph D. Ramsey
Special Faculty and Director of Research Computing
Department of Philosophy
135 Baker Hall
Carnegie Mellon University
Pittsburgh, PA 15213

jsph.ramsey@gmail.com
Office: (412) 268-8063
http://www.andrew.cmu.edu/user/jdramsey

**Comment by jdramsey** [comment]
OK, try now. If this works, we'll (I guess I'll) have to tell Dan.

Joe

On Thu, Mar 10, 2016 at 5:44 AM, Joseph Ramsey <jdramsey@andrew.cmu.edu>
wrote:

> Thanks. I looked and when FGS was unorienting parents of a node (because
> it only had one), it wasn't checking for required edges. Let me fix that.
>
> On Thu, Mar 10, 2016 at 1:09 AM, Lizzie Silver <notifications@github.com>
> wrote:
>
>> As a test case for Knowledge2, I ran FGS on the charity.txt
>> <http://www.phil.cmu.edu/projects/tetrad_download/download/workshop/Data/charity.txt>
>> data. I created a Knowledge2 object and set the first tier to be
>> "TangibilityCondition" and the second tier to include all other variables.
>>
>> The output pattern includes an undirected edge between
>> TangibilityCondition and Sympathy. Given the background knowledge, there's
>> only one possible orientation for this edge, but FGS is not inferring the
>> orientation. Is that intentional?
>>
>> I made sure the Knowledge2 object was affecting the behavior of FGS. If,
>> in addition to the tiers, I set the edge from Sympathy to
>> TangibilityCondition to be forbidden, then FGS produced a pattern with no
>> adjacency between Sympathy and TangibilityCondition.
>>
>> I'm using the latest version of the development branch of Tetrad (pulled
>> at 10pm EST on March 9, 2016).
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/cmu-phil/tetrad/issues/150>.
>>
>
>
>
> --
> Joseph D. Ramsey
> Special Faculty and Director of Research Computing
> Department of Philosophy
> 135 Baker Hall
> Carnegie Mellon University
> Pittsburgh, PA 15213
>
> jsph.ramsey@gmail.com
> Office: (412) 268-8063
> http://www.andrew.cmu.edu/user/jdramsey
>



-- 
Joseph D. Ramsey
Special Faculty and Director of Research Computing
Department of Philosophy
135 Baker Hall
Carnegie Mellon University
Pittsburgh, PA 15213

jsph.ramsey@gmail.com
Office: (412) 268-8063
http://www.andrew.cmu.edu/user/jdramsey

**Comment by lizziesilver** [comment]
From the network graph it looks like the development branch has been merged into "autistics" so I should be pulling from the autistics branch. Let me know if I have that wrong. Testing now.

**Comment by lizziesilver** [comment]
After rebasing onto the autism branch in IntelliJ Idea, I'm getting a compilation failure with the following error message:

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project tetrad-lib: Compilation failure: Compilation failure:
[ERROR] /Users/lizzie/tetrad_dev/tetrad-lib/src/main/java/edu/cmu/tetrad/graph/GraphUtils.java:[24,48] package com.sun.xml.internal.messaging.saaj.util does not exist
[ERROR] /Users/lizzie/tetrad_dev/tetrad-lib/src/main/java/edu/cmu/tetrad/graph/GraphUtils.java:[2237,36] cannot find symbol
[ERROR] symbol:   class CharReader
[ERROR] location: class edu.cmu.tetrad.graph.GraphUtils
[ERROR] -> [Help 1]
`

**Comment by jdramsey** [comment]
Oh I see... that's an oracle specific class. OK, let me think...

J

On Thu, Mar 10, 2016 at 1:29 PM, Lizzie Silver <notifications@github.com>
wrote:

> After rebasing onto the autism branch in IntelliJ Idea, I'm getting a
> compilation failure with the following error message:
>
> [ERROR] Failed to execute goal
> org.apache.maven.plugins:maven-compiler-plugin:3.3:compile
> (default-compile) on project tetrad-lib: Compilation failure: Compilation
> failure:
> [ERROR]
> /Users/lizzie/tetrad_dev/tetrad-lib/src/main/java/edu/cmu/tetrad/graph/GraphUtils.java:[24,48]
> package com.sun.xml.internal.messaging.saaj.util does not exist
> [ERROR]
> /Users/lizzie/tetrad_dev/tetrad-lib/src/main/java/edu/cmu/tetrad/graph/GraphUtils.java:[2237,36]
> cannot find symbol
> [ERROR] symbol: class CharReader
> [ERROR] location: class edu.cmu.tetrad.graph.GraphUtils
> [ERROR] -> [Help 1]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cmu-phil/tetrad/issues/150#issuecomment-194991113>.
>



-- 
Joseph D. Ramsey
Special Faculty and Director of Research Computing
Department of Philosophy
135 Baker Hall
Carnegie Mellon University
Pittsburgh, PA 15213

jsph.ramsey@gmail.com
Office: (412) 268-8063
http://www.andrew.cmu.edu/user/jdramsey

**Comment by lizziesilver** [comment]
It works! Thanks Joe! :)
