### ISSUE TITLE
Data box does not open file

### ISSUE THREAD

**Issue by processo** [cmu-phil/tetrad#1543]
I tried to load a simpe CSV file in the Data box but after I select the file nothing happens, the table remains empty.

I got the following message on the console:

Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
        at edu.pitt.dbmi.data.reader.util.TextFileUtils.inferDelimiter(TextFileUtils.java:135)
        at edu.cmu.tetradapp.editor.LoadDataSettings.getInferredDelimiter(LoadDataSettings.java:882)
        at edu.cmu.tetradapp.editor.LoadDataSettings.basicSettings(LoadDataSettings.java:503)
        at edu.cmu.tetradapp.editor.LoadDataDialog.showDataLoaderDialog(LoadDataDialog.java:165)
        at edu.cmu.tetradapp.editor.LoadDataAction.actionPerformed(LoadDataAction.java:91)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.AbstractButton.doClick(Unknown Source)
        at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
        at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by jdramsey** [comment]
Could you check your Java version number? We had some reports of this happening with low version numbers like 1.8 (Java 8);, in the ReadMe, at https://github.com/cmu-phil/tetrad, I just put a note because of this that the version number must be greater than 1.8.

**Comment by jdramsey** [comment]
To check your version number, in a terminal window on Mac or Linux or in a Command window on Windows, type java -version.

**Comment by jdramsey** [comment]
@processo BTW, did this solve your problem? If so, could you close the issue? I'm pretty sure this was the problem because many other people reported the issue, also. :)

**Comment by processo** [comment]
@jdramsey You are right. I had Java 1.8 and it works on anything newer (1.9 and above).

For those interested, [this article](https://www.morling.dev/blog/bytebuffer-and-the-dreaded-nosuchmethoderror/) explains well what is happening. Basically in Java 1.8 `ByteBuffer.clear()` is inherited from `Buffer` so it returns `Buffer` type, in later versions `ByteBuffer` has its own `clear()` method that returns `ByteBuffer` type and the mismatch caused the NoSuchMethodError.

I don't know the feature differences between Java versions but compiling Tetrad with `--release=8` (as suggested by the article) might solve the problem for all the Java 8 users.
